export enum ApplicationTypeEnum {
  MOBILE_APP = "MOBILE_APP",
  OPERATIONS_DASHBOARD = "OPERATIONS_DASHBOARD",
  SIGNUP = "SIGNUP",
  DEVELOPER_PORTAL = "DEVELOPER_PORTAL",
  API_DOCS_PORTAL = "API_DOCS_PORTAL",
}
